language: php
sudo: required

env:
  global:
  - REPO=orangehrm/orangehrm-test-environment
  - TAG=rabbitmq-3.6-management

matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t $REPO:$TAG docker-image

install:
  - docker-compose -f docker-compose.yml up -d
  - composer install
  - docker ps

script:
  - php vendor/bin/codecept run acceptance

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TAG

