language: php
sudo: required

env:
  global:
  - REPO=orangehrm/orangehrm-environment-images
  - TAG=test-7.0

matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update

install:
  - docker-compose up -d
  - composer install
  - docker ps

script:
  - php vendor/bin/codecept run unit
  - php vendor/bin/codecept run functional
  - php vendor/bin/codecept run acceptance

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TAG

