version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:test-5.6
    ports:
      - "443:443"
    volumes:
      - ./config/mysql-client:/etc/mysql
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    restart: always
    hostname: orangehrm-test-web
    container_name: test_web
