version: '2'
services:

  rabbitmq:
    image: orangehrm/orangehrm-environment-images:rabbitmq-3.6-management
    ports:
      - "15671:15671"
      - "5672:5672"
      - "5671:5671"

    restart: always
    container_name: enterprise_test_rabbitmq_3.6_management




